{
 "title": "SLO Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Alerts Firing",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}"
    }
   ]
  },
  {
   "title": "28 Day Error Budget",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "job:error_budget:slo" },
    { "expr": "job:error_budget:remaining" }
   ]
  },
  {
   "title": "Average Configured Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(example_configured_error_ratio) by (k8s_service)"
    }
   ]
  },
  {
   "title": "Prober Error Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (probe) ((rate(total[5m]) - rate(success[5m])) / rate(total[5m]))\n"
    }
   ]
  },
  {
   "title": "Example Server QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (job,k8s_service) (rate(task:http_response_total_count[1m]))"
    }
   ]
  },
  {
   "title": "Example Server Request Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(opencensus_io_http_server_latency_bucket{k8s_service=\"server\"}[1m])) by (le)"
    }
   ]
  }
 ]
}